apiVersion: apps/v1
kind: Deployment
metadata:
  name: new-eden-api
  labels:
    run: api
  namespace: webapi
spec:
  replicas: 1
  selector:
    matchLabels:
      run: api
  strategy:
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 1
    type: RollingUpdate
  template:
    metadata:
      labels:
        run: api
    spec:
      containers:
      - name: api
        image: us.gcr.io/new-eden-storage-a5c23/chingy-webapi:v1.74
        ports:
        - containerPort: 8000
---
apiVersion: v1
kind: Service
metadata:
  name: api-service
  namespace: webapi
spec:
  type: NodePort
  ports:
  - port: 8000
    targetPort: 8000
    protocol: TCP
  selector:
    run: api